/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileIndexImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPostsIndexImport } from './routes/_authenticated/posts/index'
import { Route as AuthenticatedProfileSettingsImport } from './routes/_authenticated/profile/settings'
import { Route as AuthenticatedPostsPostIdImport } from './routes/_authenticated/posts/$postId'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileIndexRoute = AuthenticatedProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPostsIndexRoute = AuthenticatedPostsIndexImport.update({
  path: '/posts/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileSettingsRoute =
  AuthenticatedProfileSettingsImport.update({
    path: '/profile/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPostsPostIdRoute = AuthenticatedPostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/posts/$postId': {
      preLoaderRoute: typeof AuthenticatedPostsPostIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile/settings': {
      preLoaderRoute: typeof AuthenticatedProfileSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/posts/': {
      preLoaderRoute: typeof AuthenticatedPostsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile/': {
      preLoaderRoute: typeof AuthenticatedProfileIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedIndexRoute,
    AuthenticatedPostsPostIdRoute,
    AuthenticatedProfileSettingsRoute,
    AuthenticatedPostsIndexRoute,
    AuthenticatedProfileIndexRoute,
  ]),
  AboutRoute,
  SignInRoute,
  SignUpRoute,
])

/* prettier-ignore-end */
